### ISSUE TITLE
String::StringToInt("0x8DB") started failing

### ISSUE THREAD

**Issue by Idrinth** [powerof3/PapyrusExtenderSSE#18]
I was heavily using StringToInt to convert hexadeximal strings to numbers. This seems to be broken with the last changes, always returning 0. Is there an intended alternative?

Running on SE for testing, but can replycate on latest Steam AE as well.

**Comment by powerof3** [comment]
Fixed, d977793298fe71bacc3ffa55c05f17726828475f
